- name: Ensure starship config directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/starship"
    state: directory

- name: Symlink starship config
  file:
    src: "{{ dotfiles_path }}/.config/starship"
    dest: "{{ lookup('env', 'HOME') }}/.config/starship"
    state: link
    force: true

- name: Ensure STARSHIP_CONFIG is set in config.nu
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.config/nushell/config.nu"
    line: let-env STARSHIP_CONFIG = $HOME/.config/starship/starship.toml
    state: present
