dotfiles_path: "{{ lookup('env', 'DOTFILES_PATH') | default(lookup('env', 'HOME') + '/dotfiles', true) }}"

home: "{{ ansible_facts['env']['HOME'] }}"
homebrew_prefix: "{{ '/opt/homebrew' if ansible_facts['architecture'] == 'arm64' else '/usr/local' }}"
homebrew_bin: "{{ homebrew_prefix }}/bin"

target_shell: "{{ homebrew_bin }}/nu"

homebrew_packages:
  - git
  - zoxide
  - carapace
  - starship
  - nushell
  - zellij
  - mise
  - ripgrep
  - fzf
  - fd
  - bat
  - eza
  - neovim
  - watchman
  - btop

homebrew_casks:
  - ghostty

mise_tools:
  node: "latest"
  bun: "latest"
