
- name: Install tmux via Homebrew
  homebrew:
    name: tmux
    state: present

- name: Remove existing tmux config
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/tmux"
    state: absent

- name: Symlink tmux config
  file:
    src: "{{ dotfiles_path }}/.config/tmux"
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux"
    state: link
    force: true
