keychain_secrets:
  - service: "AKKA_LICENSE_KEY"
    prompt: "Akka License Key"
    description: "Clé de licence Akka (Lightbend)"
  # add new secrets here (example):
  # - service: "GITHUB_TOKEN"
  #   prompt: "GitHub Personal Access Token"
  #   description: "Token GitHub"
