- hosts: localhost
  connection: local
  vars:
    dotfiles_path: "{{ lookup('env', 'DOTFILES_PATH') | default(ansible_env.HOME + '/dotfiles', true) }}"
  roles:
    - { role: starship, tags: ["starship"] }
    - { role: nushell, tags: ["nushell"] }
    - { role: zellij, tags: ["zellij"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: ghostty, tags: ["ghostty"] }
