- hosts: localhost
  connection: local

  vars_files:
    - group_vars/all.yml

  roles:
    - { role: base, tags: ["base", "always"] }
    - { role: homebrew, tags: ["homebrew"] }
    - { role: mise, tags: ["mise"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: ghostty, tags: ["ghostty"] }
    - { role: nushell, tags: ["nushell"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: secrets, tags: ["secrets"] }
    - { role: stow, tags: ["stow"] }
